# Generated by Django 4.0.2 on 2022-02-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_value', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('conversions', models.IntegerField()),
                ('search_term', models.CharField(max_length=250)),
                ('roas', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('date', models.DateField()),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.adgroup')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.campaign')),
            ],
            options={
                'ordering': ['-roas'],
            },
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.campaign'),
        ),
    ]
